name: Deploy project

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Authenticate using SFLABS_PROD"
        shell: bash
        run: |
          echo ${{ secrets.SFLABS_PROD }} | sf org login sfdx-url -s -u

      - name: "Deploy"
        run: |
          sf project deploy start -d force-app/ -l RunLocalTests -w 30
