name: Validate against SF Labs org

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize]
    paths:
      - "force-app/**"
jobs:
  salesforce-code-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      # PREREQUISITES - Only needed if runner doesn't already satisfy these requirements
      - name: Ensure node v20 or greater
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v4
        with:
          java-version: ">=11"
          distribution: "zulu"
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.10"

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json --config-file ./code-analyzer.yml
          results-artifact-name: salesforce-code-analyzer-results

      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1

  lwc-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npm run test:unit -- --coverage

      - name: Enforce Coverage Threshold
        run: |
          COVERAGE=$(npx jest --coverage --json --outputFile=coverage-summary.json)
          THRESHOLD=100
          ACTUAL=$(jq '.total.lines.pct' coverage-summary.json)
          if (( $(echo "$ACTUAL < $THRESHOLD" | bc -l) )); then
            echo "Code coverage $ACTUAL% is below threshold $THRESHOLD%"
            exit 1
          fi

  lwc-mutation-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npm run test:unit -- --coverage

      - name: Enforce Coverage Threshold
        run: |
          COVERAGE=$(npx jest --coverage --json --outputFile=coverage-summary.json)
          THRESHOLD=80
          ACTUAL=$(jq '.total.lines.pct' coverage-summary.json)
          if (( $(echo "$ACTUAL < $THRESHOLD" | bc -l) )); then
            echo "Code coverage $ACTUAL% is below threshold $THRESHOLD%"
            exit 1
          fi

      - name: Run Mocha Mutation Tests
        run: npx stryker run

      - name: Check Mutation Score
        run: |
          SCORE=$(jq '.mutationScore' reports/mutation/mutation.json)
          THRESHOLD=70
          if (( $(echo "$SCORE < $THRESHOLD" | bc -l) )); then
            echo "Mutation testing score $SCORE% is below threshold $THRESHOLD%"
            exit 1
          fi

  validate-deployment:
    runs-on: ubuntu-latest
    needs: salesforce-code-analyzer
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Authenticate using SFLABS_DEV"
        run: |
          echo ${{ secrets.SFLABS_DEV }} | sf org login sfdx-url -s -u

      - name: "Validate"
        run: |
          sf project deploy validate -d force-app/ -l RunLocalTests -w 30
